### ISSUE TITLE
.proto files checked into repo

### ISSUE THREAD

**Issue by disturbing** [kintoproj/kinto-dashboard#3]
**Is your feature request related to a problem? Please describe.**
Depending on proto files from a required 3rd party repo works great for internal-dev, but would prefer ease of use for open source.

**Describe the solution you'd like**
Create a new folder called proto and have a github submodule checkout and updated on new feature/bug releases when the proto file(s) have changed.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nandiheath** [comment]
we already have the `refs/kinto-core` repo that is checked out as git submodule
we have also a guide [here](https://github.com/kintoproj/kinto-dashboard#generating-types-from-proto-files)
